name: GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Modify this command based on your project setup

    - name: Deploy
      run: |
        git config --global user.name ${{ secrets.GITHUB_ACTOR }}
        git config --global user.email ${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com
        git remote add origin-deploy https://github.com/$GITHUB_REPOSITORY.git
        git checkout -b gh-pages
        git pull origin gh-pages
        git merge --no-edit $GITHUB_SHA
        git push --force origin-deploy gh-pages

  deploy-deploy:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to GitHub Pages
      run: echo "Deployment complete."

